### PR TITLE
fix(resource): also ignore no such element err

### LINKED ISSUE #193: Patch targets can't add elements to array
### What happened?

When using the `PatchDesired` target, I can't add elements array. It fails with errors similar to:

```
crossplane: error: cannot render composite resource: pipeline step "ensure-table-keys-and-indexes-configuration" returned a fatal result: cannot process xr and state with the pipeline output in *v1.RunFunctionResponse: cannot set data existing desired composed object: getting spec.forProvider.globalSecondaryIndex[0].nonKeyAttributes[1]:foo in xr failed: spec.forProvider.globalSecondaryIndex[0].nonKeyAttributes[1]: no such element
```

### How can we reproduce it?

I don't have a minimal reproducer, but I believe I have found the issue. I'll submit a fix, and if that doesn't seem reasonable, I'll work on stripping away my org's stuff from the composition/XR I'm facing this problem with.

### What environment did it happen in?
Function version:  master

### PR DESCRIPTION
**Pull request by LCaparelli**
### Description of your changes

Since `crossplane-runtime` might also return a "no such element" error, we must also interpret that case, and ignore it in order to patch the existing array with a new element.

https://github.com/crossplane/crossplane-runtime/blob/19d95a69cc03690c4b867ff91d89681fcf872a93/pkg/fieldpath/paved.go#L124-L126

Previous to this change, we only dealt with the "no such field" error:

https://github.com/crossplane/crossplane-runtime/blob/19d95a69cc03690c4b867ff91d89681fcf872a93/pkg/fieldpath/paved.go#L135-L137

In this case, the lib provides an exported method to check for not found without the need for us to compare against the error's string. This way we also nicely decouple our logic from implementation details on `crossplane-runtime`.

Fixes #193 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

File: pkg/resource/res_test.go [hunk 1]
```diff
@@ -71,3 +72,43 @@ func TestObjToRawExtension(t *testing.T) {
...
+		o         any
+		overwrite bool
+	}
+	tests := []struct {
+		name    string
+		args    args
+		wantErr bool
+	}{
+		{
+			name: "Should create a new element on existing array",
```
Comment (LCaparelli) [inline pkg/resource/res_test.go:89]: This scenario fails on main

**Comment by LCaparelli** [comment]
Thank you @Peefy, that was quick! 

When could we expect a release of this fix? I was hoping to get it deployed for something I'm working on this week. We can adapt our logic to avoid the bug, or use a fork, but just wondering if it makes sense to wait for the release. Thanks again!
